### ISSUE TITLE
Can two workflows share the same model with each other?

### ISSUE THREAD

**Issue by yurkoff-mv** [pytorch/serve#1103]
Continuing my previous post: [How i do models chain processing and batch processing for analyzing text data?](https://github.com/pytorch/serve/issues/1055)

Can I create two workflows using the same RoBERTa base model to perform two different tasks, let's say the classifier_model and summarizer_model? I would like to be able to share the base model with two workflows.

I am trying to register two workflows: wf_classifier.war and wf_summarizer.war. The first one is registered and the second one is not.

[log.log](https://github.com/pytorch/serve/files/6562664/log.log)

**wf_classifier.war**
```
models:
    min-workers: 1
    max-workers: 1
    batch-size: 1
    max-batch-delay: 1000
    retry-attempts: 5
    timeout-ms: 300000

    roberta:
      url: roberta_base.mar

    classifier:
      url: classifier.mar

dag:
  roberta: [classifier]
```

**wf_summarizer.war**
```
models:
    min-workers: 1
    max-workers: 1
    batch-size: 1
    max-batch-delay: 1000
    retry-attempts: 5
    timeout-ms: 300000

    roberta:
      url: roberta_base.mar

    summarizer:
      url: summarizer.mar

dag:
  roberta_base: [summarizer]
```
