### ISSUE TITLE
Non-default config settings and keeping settings from management api

### ISSUE THREAD

**Issue by denck007** [pytorch/serve#1542]
## Context
We are specifying a ts-config file so that each model can install its own dependencies, and are adding models via the management API. This works well but when the server is restarted, the models that are added via the API don't come back up because the docker-compose file specifies a ts-config file that doesn't list the models.

Is there a way to tell torchserve to default to the latest snapshot file and only fallback to the default one if none exist?

## Environment
Relevant portion of docker-compose file
```
  torchserve:
    image: pytorch/torchserve:0.5.3-gpu
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - /storage/models:/models
    command: ["torchserve", "--start", "--model-store /models", "--ts-config /models/config.properties"]
```

Contents of `/models/config.properties` 
```
install_py_dep_per_model=true
enable_metrics_api=true
inference_address=http\://0.0.0.0\:8080
management_address=http\://0.0.0.0\:8081
metrics_address=http\://0.0.0.0\:8082
```

## Desired Behavior
Would like running these commands:
```
docker-compose up -d
curl --request POST 'http://0.0.0.0:8081/models?url=model.mar'
docker-compose down && docker-compose up -d
curl --request GET 'http://0.0.0.0:8081/models'
```
To output:
```
{
   "models": [
    {
      "modelName": "model",
      "modelUrl": "model.mar"
    }
  ]
}
```

What is actually output:
```
{
   "models": []
}
```
## Options I have looked at
1. Remove the --ts-config option after the first run of the server
    * Don't like this as manual intervention is required when setting up the server
2. Place a snapshot file into ./logs/config/
    * To persist logs would have to mount using `nocopy`. Seems like bad practice to require a nocopy mount out of the box
    * Will probably go this route, but it seems odd to manually put a file in an automatic snapshot directory
