### ISSUE TITLE
Adding `pre-commit`

### ISSUE THREAD

**Issue by sudomaze** [pytorch/serve#1598]
## Is your feature request related to a problem? Please describe.

To ensure the quality of commits, have a stage to be run before any commit.

## Describe the solution
Utilizing [`pre-commit`](https://pre-commit.com/), which is a Git hook that is triggered on every commit to automatically detect issues in code. 

I have used `pre-commit` and there are multiple hooks that can be added, such as:
- [pre-commit-hooks](https://github.com/pre-commit/pre-commit-hooks) - set of useful hooks. For more hooks, check [this](https://github.com/pre-commit/pre-commit-hooks#hooks-available)
	- `check-ast` - Simply check whether files parse as valid python.
	- `check-builtin-literals` - Require literal syntax when initializing empty or zero Python builtin types.
	- `check-case-conflict` - Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
	- `check-docstring-first` - Checks for a common error of placing code before the docstring.
	- `check-merge-conflict` - Check for files that contain merge conflict strings.
	- `check-json` - Attempts to load all json files to verify syntax.
	- `check-toml` - Attempts to load all TOML files to verify syntax.
	- `check-yaml` - Attempts to load all yaml files to verify syntax.
	- `end-of-file-fixer` - Makes sure files end in a newline and only a newline.
	- `mixed-line-ending` - Replaces or checks mixed line ending.
	- `trailing-whitespace` - Trims trailing whitespace.
	- `check-vcs-permalinks` - Ensures that links to vcs websites are permalinks.
	- `check-shebang-scripts-are-executable` - Checks that scripts with shebangs are executable.
- [pygrep-hooks](https://github.com/pre-commit/pygrep-hooks) -  regex based pre-commit hooks. For more hooks, check [this](https://github.com/pre-commit/pygrep-hooks#provided-hooks)
	- `python-no-log-warn` - A quick check for the deprecated `.warn()` method of python loggers
	- `python-use-type-annotations` - Enforce that python3.6+ type annotations are used instead of type comments
- [pycln](https://github.com/hadialqattan/pycln) - A formatter for finding and removing unused import statements
- [black](https://github.com/psf/black) - Python code formatter.
- [isort](https://github.com/PyCQA/isort) - Sort imports alphabetically, and automatically separated into sections and by type

The only thing that is needed is adding `pre-commit` as a hook to Git and create a config similar to this:

<details>

<summary><code>.pre-commit-config.yaml</code></summary>

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-vcs-permalinks
      - id: check-shebang-scripts-are-executable
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-mock-methods
      - id: python-no-log-warn
      - id: python-use-type-annotations
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.5
    hooks:
      - id: pycln
        args: [--all]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
        exclude: output|data
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: output|data
        args: ["--profile", "black"]
```
</details>

---
I can work on adding `pre-commit` after I get approval for adding this feature.
