### ISSUE TITLE
Support GPU and CPU models on one docker container

### ISSUE THREAD

**Issue by Xianlilxl** [pytorch/serve#2394]
### 🐛 Describe the bug

I am serving 3 models on my computer with GPU capacity, Torchserve is deployed as a docker container:
```
  server:
    image: pytorch/torchserve:test-gpu
    container_name: {container_name}
    restart: always
    volumes:
      - type: bind
        source: ./model_store
        target: /home/model-server/model-store
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail http://server:8080/ping || exit 1"
        ]
      interval: 30s
      timeout: 15s
      retries: 5
    ports:
      - 8080:8080
      - 8081:8081
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
```
I want to serve one of the models on CPU and 2 others on GPU, now supported by Torchserve 0.8.0. I am following the instruction from the Torch Model Archiver README file:[https://github.com/pytorch/serve/tree/master/model-archiver#config-file](url) in order to define our CPU model like the following:
```
minWorkers: 1
maxWorkers: 2
batchSize: 1
deviceType: CPU
```
But when I describe my model I see the workers are still on GPU, the result is shown on the section **Error logs**. So I would like to know if it is possible to deploy both GPU and CPU models on one docker container. 

### Error logs

Here is the result returning by `curl http://localhost:8081/models/{model_name}`
```
[
  {
    "modelName": "{model_name}",
    "modelVersion": "1.1",
    "modelUrl": "{model_name}.mar",
    "runtime": "python",
    "minWorkers": 1,
    "maxWorkers": 2,
    "batchSize": 1,
    "maxBatchDelay": 100,
    "loadedAtStartup": true,
    "workers": [
      {
        "id": "9000",
        "startTime": "2023-06-06T07:26:35.267Z",
        "status": "READY",
        "memoryUsage": 6423101440,
        "pid": 87,
        "gpu": true,
        "gpuUsage": "gpuId::0 utilization.gpu [%]::0 % utilization.memory [%]::0 % memory.used [MiB]::7998 MiB"
      }
    ]
  }
]
```

### Installation instructions

Installed using source? [yes/no]: yes.
Are you using Docker: yes
Is it a CPU or GPU environment?: GPU and CPU
Using a default/custom handler?: custom handler.
What kind of model is it e.g. vision, text, audio?: text model on CPU, vision model and generative model on GPU
Are you planning to use local models from model-store or public url being used e.g. from S3 bucket etc.? local models from model-store

### Model Packaing

I am using this command to package my cpu model with custom handler: 
```
torch-model-archiver \
    --model-name {model_name} \
    --version 1.1 \
    --handler handler.py \
    --extra-files model.zip \
    --export-path . \
    --config-file config.yaml
 ```

### config.properties

```
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082
number_of_netty_threads=32
job_queue_size=1000
max_request_size=13107000
max_response_size=13107000
model_store=/home/model-server/model-store
install_py_dep_per_model=false
default_workers_per_model=2
load_models=all
```

### Versions

```
------------------------------------------------------------------------------------------
Environment headers
------------------------------------------------------------------------------------------
Torchserve branch: 

torchserve==0.8.0
torch-model-archiver==0.8.0

Python version: 3.8 (64-bit runtime)
Python executable: /home/venv/bin/python

Versions of relevant python libraries:
captum==0.6.0
numpy==1.24.3
nvgpu==0.10.0
psutil==5.9.5
requests==2.31.0
requests-oauthlib==1.3.1
sentence-transformers==2.0.0
sentencepiece==0.1.91
torch==1.10.0+cu113
torch-model-archiver==0.8.0
torchserve==0.8.0
torchtext==0.15.2
torchvision==0.11.0+cu113
transformers==4.19.2
wheel==0.40.0
torch==1.10.0+cu113
torchtext==0.15.2
torchvision==0.11.0+cu113
**Warning: torchaudio not present ..

Java Version:


OS: N/A
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: N/A
CMake version: N/A

Is CUDA available: Yes
CUDA runtime version: 11.3.109
GPU models and configuration: 
GPU 0: NVIDIA RTX A4000 Laptop GPU
Nvidia driver version: 527.27
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.0
```

### Repro instructions

1. Package models like presented before
2. Build the torchserve using [https://github.com/pytorch/serve/blob/master/docker/build_image.sh](url)
3. Write the torchserve part in the docker compose file like presented before
4. docker compose up
