### ISSUE TITLE
io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

### ISSUE THREAD

**Issue by KD1994** [pytorch/serve#3279]
Hello team,

I'm unable to understand this error, as it is being thrown after completion of the entire workflow!!

Something like this (logs are from docker logs command):
```
pygsl_prod_service.0.q3shploty9kt@nav0789    | 2024-08-05T16:52:12,397 [INFO ] wf-manager-thread-0 ACCESS_LOG - /10.0.0.2:46572 "POST /wfpredict/check_extract HTTP/1.1" 200 930926
pygsl_prod_service.0.q3shploty9kt@nav0789    | 2024-08-05T16:52:12,398 [INFO ] wf-manager-thread-0 TS_METRICS - Requests2XX.Count:1.0|#Level:Host|#hostname:Unknown,timestamp:1722856932
pygsl_prod_service.0.q3shploty9kt@nav0789    | 2024-08-05T16:52:12,402 [ERROR] epollEventLoopGroup-3-2 org.pytorch.serve.http.HttpRequestHandler -
pygsl_prod_service.0.q3shploty9kt@nav0789    | io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
```

* Question:

1. Is this error because of the client API call is not waiting for response? (The timeout on client end is `30 minutes` and usually a request takes around 12-15 minutes.)
2. What should be the correct values for `number_of_netty_threads`, `netty_client_threads`, `job_queue_size`. I set these values after looking at this [comment](https://github.com/pytorch/serve/issues/1360#issuecomment-990146154)

TS config:

* model-config.yaml

```yaml
maxBatchDelay: 10000000
responseTimeout: 10000000
```

* workflow.yaml

```yaml
models:
    min-workers: 1
    max-workers: 2
    max-batch-delay: 10000000
    retry-attempts: 1
    timeout-ms: 3000000

    m1:
      url: mode-1.mar

    m2:
      url: model-2.mar

    m3:
      url: model-3.mar

    m4:
      url: model-4.mar

    m5:
      url: model-5.mar
  
dag:
  pre_processing: [m1]
  m1: [m2]
  m2: [m3]
  m3: [m4]
  m4: [m5]
  m5: [post_processing]
```

* config.properties

```properties
inference_address=http://0.0.0.0:8080
management_address=http://0.0.0.0:8081
metrics_address=http://0.0.0.0:8082

# management
number_of_netty_threads=16    # default count shown is 0, so I added this to get the solution of the connection error.
netty_client_threads=16             # default count shown is 0, so I added this to get the solution of the connection error.
default_response_timeout=10000000
# default_workers_per_model=2
max_request_size=65535000
max_response_size=65535000

load_models=
model_store=model_store
workflow_store=wf_store

enable_envvars_config=true
disable_system_metrics=true
job_queue_size=1

```

* Python Packages:

```text
torch==1.13.1+cu117
torchvision==0.14.1+cu117
torchaudio==0.13.1+cu117
torchserve==0.10.0
torch-model-archiver==0.10.0
torch-workflow-archiver==0.2.12
nvgpu==0.10.0
captum==0.7.0
```

Appreciate your help guys!
Thanks.
